<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_test" Id="{3d4c6f9d-e028-4b31-a721-174ac5903662}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_test
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>