<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{1a4896df-f497-49c3-94ec-91bd7519a090}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	toto : BOOL;
	toto1 : BOOL;
	fbtest : FB_test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[toto := NOT toto;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>